### PR TITLE
Add global headers and use in each requests.get 

### PR DESCRIPTION
**Pull request by turbatuandrei**
https://github.com/xofbd/wqu_project_s202009/issues/7

@xofbd

Changed local variable headers from get_geolocation() into global headers and used it in each requests.get

### CODE REVIEW

**Review by xofbd — CHANGES_REQUESTED** [review]
Two things.

1. I've integrating testing to this repo. In other words, a set of tests are run to make sure if a PR is safe to merge into master. Those tests are both to make sure things aren't broken (although we do need more tests) and whether the code satisfies the Python standard convention (PEP8). Look at the PR page and you'll see Travis CI; that's the service I am using for testing. Notice how it's failing. Take a look at see why it's failing and make the fix.

1. There's a convention to write constants as ALL CAPS. That way, it's easier to read. For example, if I see `HEADERS`, I know that that is a constant and probably defined in the global scope.

**Comment by turbatuandrei** [comment]
Done :)

**Comment by xofbd** [comment]
@turbatuandrei Cool, looks like it's past testing. Note, you can run the tests yourself by running `make tests` or `make test-flake8` and `make test-unit`. That way, you can check what will fail before pushing.

One last thing, do you mind rebasing and setting that new commit as "fixup". That way, the history will only show one commit.

**Comment by turbatuandrei** [comment]
@xofbd I rebased it.

Thanks for the tips about running tests.

**Pull request merged**
